routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\QrController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HireController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TankerController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\CheckListNrController;
use App\Http\Controllers\CheckListRigidController;
use App\Http\Controllers\CheckListMilkController;
use App\Http\Controllers\CheckListFoodController;
use App\Http\Controllers\CheckListVacuumController;
use App\Http\Controllers\CheckListWasteController;
use App\Http\Controllers\CheckListPetrolController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LinkController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\TCLEmailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great! Note
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');



Route::get('/newhiremockup', function () {
    return view('newbooking');
});

Route::get('/checkoutmockup', function () {
    return view('checkout');
});
Route::get('/rigid', function () {
    return view('rigid');
});

Auth::routes();

Route::post('videosStore', 'App\Http\Controllers\MediaController@saveVideo')->name('videos.store');
Route::post('imagesStore', 'App\Http\Controllers\MediaController@saveImage')->name('images.store');

Route::get('contract/{uuid}', [ContractController::class, 'customerSign'])->name('contract_link');
Route::put('contract/{hire}',  [ContractController::class, 'store'])->name('contract.store');

Route::get('checkListNR/{uuid}', [ContractController::class, 'checklistNr'])->name('checklist_nr_link');
Route::get('checkListRigid/{uuid}', [ContractController::class, 'checklistRigid'])->name('checklist_rigid_link');
Route::get('checkListMilk/{uuid}', [ContractController::class, 'checklistMilk'])->name('checklist_milk_link');
Route::get('checkListFood/{uuid}', [ContractController::class, 'checklistFood'])->name('checklist_food_link');
Route::get('checkListVacuum/{uuid}', [ContractController::class, 'checklistVacuum'])->name('checklist_vacuum_link');
Route::get('checkListWaste/{uuid}', [ContractController::class, 'checklistWaste'])->name('checklist_waste_link');
Route::get('checkListPetrol/{uuid}', [ContractController::class, 'checklistPetrol'])->name('checklist_petrol_link');

Route::get('sendMail', [TCLEmailController::class, 'sendHireEmailToCustomer'])->name('email');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::get('home', [HomeController::class, 'index'])->name('home');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('settings', SettingController::class);
        Route::resource('tankers', TankerController::class);
        Route::resource('qrs', QrController::class);
        Route::resource('logs', LogController::class);
        Route::resource('companies', CompanyController::class);
        Route::resource('users', UserController::class);
        Route::resource('hires', HireController::class);
        Route::resource('check-list-n-rs', CheckListNrController::class);
        Route::resource('check-list-rigids', CheckListRigidController::class);
        Route::resource('check-list-milks', CheckListMilkController::class);
        Route::resource('check-list-foods', CheckListFoodController::class);
        Route::resource('check-list-vacuums', CheckListVacuumController::class);
        Route::resource('check-list-wastes', CheckListWasteController::class);
        Route::resource('check-list-petrols', CheckListPetrolController::class);
        Route::get('link/{fleet_num}', [LinkController::class, 'showTanker']);

        Route::get('user/profile', [ProfileController::class, 'index'])->name('user.profile');
        Route::post('user/avatarUpload', [ProfileController::class, 'avatarUpload'])->name('user.avatarUpload');
        Route::post('user/profileUpdate', [ProfileController::class, 'profileUpdate'])->name('user.profileUpdate');
        Route::post('user/jobInfoUpdate', [ProfileController::class, 'jobInfoUpdate'])->name('user.jobInfoUpdate');
        Route::post('user/changePwd', [ProfileController::class, 'changePwd'])->name('user.changePwd');        
        Route::post('tankers/archive', [TankerController::class, 'archive'])->name('tankers.archive');
        Route::post('tankers/refresh', [TankerController::class, 'refresh'])->name('tankers.refresh');
        Route::post('hires/documentUpload', [HireController::class, 'documentUpload'])->name('hires.documentUpload');
    });

Route::get('/{any}', function(){
    return redirect()->route("welcome");
});

app/Models/CheckListRigid.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CheckListRigid extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'status',
        'uuid',

        'paintwork',
        'cab_seat',
        'glass_mirrors',
        'valves_controls',
        'rear_bumper',
        'wings_stays',
        'lights',
        'vaccum_pump',
        'levels',
        'camera_operation',
        'cab_inside_out',
        'side_guards',
        'book_pack',
        
        'last_known_product',
        'mileage',
        'vessel_condition',
        'fuel_level',
        'notes',

        /// Video walk around fields
        'int_video',
        'ext_video',
        
        //Cleaning Certificate
        'cleaning_status',
        'cleaning_check',

        //Tyres check fields
        'tyres_1_1',
        'tyres_1_2',
        'tyres_1_3',
        'tyres_1_4',
        'tyres_2_1',
        'tyres_2_2',
        'tyres_2_3',
        'tyres_3_1',
        'tyres_3_2',
        'tyres_3_3',
        'tyres_4_1',
        'tyres_4_2',
        'tyres_4_3',
        'tyres_4_4',
        
        //Tanker Inspection fields
        'int_splat',
        'ext_splat_right',
        'ext_splat_left',
        'ext_splat_rear',
        'ext_splat_front',

        // Extra fields for signature
        'hirer_behalf',
        'tcl_behalf',

        'checklist_type',
        'hirer_name',
        'hirer_position',
        'hirer_signature',
        'hirer_sign_date',
        'tcl_name',
        'tcl_position',
        'tcl_signature',
        'tcl_sign_date',
        'hire_id',
        'link',
        'supervisor_signature',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'check_list_rigids';

    protected $casts = [
        'hirer_sign_date' => 'datetime',
        'tcl_sign_date' => 'datetime',
    ];

    public function hire()
    {
        return $this->belongsTo(Hire::class);
    }
}

app/Http/Controllers/CheckListRigidController.php
<?php

namespace App\Http\Controllers;


use App\Models\Hire;
use App\Models\Tanker;
use Illuminate\Http\Request;
use App\Models\CheckListRigid;
use App\Http\Requests\CheckListRigidStoreRequest;
use App\Http\Requests\CheckListRigidUpdateRequest;
use Illuminate\Support\Str;

use Illuminate\Support\Facades\Storage;
use Datetime;

class CheckListRigidController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', CheckListRigid::class);

        $search = $request->get('search', '');

        $checkListRigids = CheckListRigid::search($search)
            ->latest()
            ->paginate(20);

        return view(
            'app.check_list_rigids.index',
            compact('checkListRigids', 'search')
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', CheckListRigid::class);

        $hire_id = $request->hire_id;
        $hire = Hire::find($hire_id);
        $check_type = $request->check_list_type;
        session(['hire_id' => $hire_id]);
        session(['check_type' => $check_type]);

        return view('app.check_list_rigids.create', compact('hire', 'check_type'));
    }


    
    public function sendMail($checkList) {
        $details = [
            'hirer_name' => $checkList->hirer_name,
            'link_url' => route('checklist_rigid_link', ['uuid' => $checkList->uuid])
        ];
        $email_address = $checkList->hire->company->email;
        // \Mail::to("italexx.ua@gmail.com")->send(new \App\Mail\SendCheckListRigidMail($details));
        \Mail::to($email_address)->send(new \App\Mail\SendCheckListRigidMail($details));
    }

    
    public function validateCheckboxes($request, $validated) {
        $validated['paintwork'] = isset($request->paintwork) ? $request->paintwork == 'on' ? true : false : false;
        $validated['cab_seat'] = isset($request->cab_seat) ? $request->cab_seat == 'on' ? true : false : false;
        $validated['glass_mirrors'] = isset($request->glass_mirrors) ? $request->glass_mirrors == 'on' ? true : false : false;
        $validated['valves_controls'] = isset($request->valves_controls) ? $request->valves_controls == 'on' ? true : false : false;
        $validated['rear_bumper'] = isset($request->rear_bumper) ? $request->rear_bumper == 'on' ? true : false : false;
        $validated['wings_stays'] = isset($request->wings_stays) ? $request->wings_stays == 'on' ? true : false : false;
        $validated['lights'] = isset($request->lights) ? $request->lights == 'on' ? true : false : false;
        $validated['vaccum_pump'] = isset($request->vaccum_pump) ? $request->vaccum_pump == 'on' ? true : false : false;
        $validated['levels'] = isset($request->levels) ? $request->levels == 'on' ? true : false : false;
        $validated['camera_operation'] = isset($request->camera_operation) ? $request->camera_operation == 'on' ? true : false : false;
        $validated['cab_inside_out'] = isset($request->cab_inside_out) ? $request->cab_inside_out == 'on' ? true : false : false;
        $validated['side_guards'] = isset($request->side_guards) ? $request->side_guards == 'on' ? true : false : false;
        $validated['book_pack'] = isset($request->book_pack) ? $request->book_pack == 'on' ? true : false : false;
        
        $validated['cleaning_check'] = isset($request->cleaning_check) ? $request->cleaning_check == 'on' ? true : false : false;
        return $validated;
    }



    /**
     * @param \App\Http\Requests\CheckListRigidStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CheckListRigidStoreRequest $request)
    {
        $this->authorize('create', CheckListRigid::class);        
        $validated = $request->validated();
        $validated = $this->validateCheckboxes($request, $validated); 
        $validated['uuid'] = Str::uuid();
        $validated['hire_id'] = session('hire_id');

        $validated['ext_splat_right'] = str_replace(env('APP_URL'), '', $validated['ext_splat_right']);
        $validated['ext_splat_left'] = str_replace(env('APP_URL'), '', $validated['ext_splat_left']);
        $validated['ext_splat_rear'] = str_replace(env('APP_URL'), '', $validated['ext_splat_rear']);
        $validated['ext_splat_front'] = str_replace(env('APP_URL'), '', $validated['ext_splat_front']);
        $validated['int_splat'] = str_replace(env('APP_URL'), '', $validated['int_splat']);
        
        $validated['int_video'] = str_replace(env('APP_URL'), '', $validated['int_video']);
        $validated['ext_video'] = str_replace(env('APP_URL'), '', $validated['ext_video']);
        
        $validated['hirer_signature'] = str_replace(env('APP_URL'), '', $validated['hirer_signature']);
        $validated['tcl_signature'] = str_replace(env('APP_URL'), '', $validated['tcl_signature']);
        $validated['supervisor_signature'] = str_replace(env('APP_URL'), '', $validated['supervisor_signature']);

        if($request->hasFile('cleaning_status')) {            
            $image = $request->file('cleaning_status');            
            $date = new DateTime();
            $new_image_name = $date->getTimestamp();                                    
            $file_name = $new_image_name.'.'.$image->guessExtension();                        
            $path = $image->storeAs(
                'public/uploads/cleaning_status', $file_name
            );                
            $url = '/storage/uploads/cleaning_status/'.$file_name;            
            $validated['cleaning_status'] = $url;
        }   
        $checkListRigid = CheckListRigid::create($validated);
        $checkListRigid->supervisor_signature = $request->supervisor_signature;
        $checkListRigid->save();
        
        $hire = null;
        if($request->hirer_signature != "/img/sign.png" && $request->tcl_signature != "/img/sign.png" ) {
            $checkListRigid->status = "signed";
            $checkListRigid->update($validated);
            $hire = Hire::find($checkListRigid->hire_id);
            if($checkListRigid->checklist_type == "On") {
                $hire->status = "onHire";
            }
            if($checkListRigid->checklist_type == "Off") {
                $hire->status = "offHire";

                $tanker = Tanker::find($hire->tanker_id);
                $tanker->usage = false;
                $tanker->save();
            }
            $hire->save();
            $this->sendMail($checkListRigid);

            return redirect()->route('hires.index')->withSuccess(__('crud.common.created'));
        }
        if(!$hire)
        {
            $hire_id = session('hire_id');
            $hire = Hire::find($hire_id);
        }
        $tanker = $hire->tanker;
        
        $tanker->ext_splat_left = $validated['ext_splat_left'];
        $tanker->ext_splat_front = $validated['ext_splat_front'];
        $tanker->ext_splat_rear = $validated['ext_splat_rear'];
        $tanker->ext_splat_right = $validated['ext_splat_right'];
        $tanker->int_splat = $validated['int_splat'];
        $tanker->save();

        return redirect()
            ->route('check-list-rigids.edit', $checkListRigid)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\CheckListRigid $checkListRigid
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, CheckListRigid $checkListRigid)
    {
        $this->authorize('view', $checkListRigid);

        return view('app.check_list_rigids.show', compact('checkListRigid'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\CheckListRigid $checkListRigid
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, CheckListRigid $checkListRigid)
    {
        $this->authorize('update', $checkListRigid);
        
        $hires = Hire::pluck('start_date', 'id');

        $hire_id = session('hire_id');
        $check_type = session('check_type');
        $hire = Hire::find($hire_id);


        return view('app.check_list_rigids.edit', compact('checkListRigid', 'hire', 'check_type'));
    }

    /**
     * @param \App\Http\Requests\CheckListRigidUpdateRequest $request
     * @param \App\Models\CheckListRigid $checkListRigid
     * @return \Illuminate\Http\Response
     */
    public function update(
        CheckListRigidUpdateRequest $request,
        CheckListRigid $checkListRigid
    ) {
        $this->authorize('update', $checkListRigid);
        $checkListRigid->supervisor_signature = $request->supervisor_signature;
        $checkListRigid->save();
        $validated = $request->validated();
        $validated = $this->validateCheckboxes($request, $validated);

        $validated['ext_splat_right'] = str_replace(env('APP_URL'), '', $validated['ext_splat_right']);
        $validated['ext_splat_left'] = str_replace(env('APP_URL'), '', $validated['ext_splat_left']);
        $validated['ext_splat_rear'] = str_replace(env('APP_URL'), '', $validated['ext_splat_rear']);
        $validated['ext_splat_front'] = str_replace(env('APP_URL'), '', $validated['ext_splat_front']);
        $validated['int_splat'] = str_replace(env('APP_URL'), '', $validated['int_splat']);
        
        $validated['int_video'] = str_replace(env('APP_URL'), '', $validated['int_video']);
        $validated['ext_video'] = str_replace(env('APP_URL'), '', $validated['ext_video']);
        
        $validated['hirer_signature'] = str_replace(env('APP_URL'), '', $validated['hirer_signature']);
        $validated['tcl_signature'] = str_replace(env('APP_URL'), '', $validated['tcl_signature']);

resources/views/app/check_list_rigids/create.blade.php
@extends('layouts.app')

@section('content')

<main class="-mt-28 pb-8">
    <section aria-labelledby="hire-contract">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <x-slot name="title">
                <a href="{{ route('check-list-rigids.index') }}" class="mr-4"
                    ><i class="mr-1 icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.check_list_rigids.create_title')
            </x-slot>

            <form
                method="POST"
                action="{{ route('check-list-rigids.store') }}"
                class="mt-4"
                role="form"
                enctype="multipart/form-data"
                id="check-list-rigids-form"
            >
                <div class="mb-10 rounded-lg bg-white overflow-hidden shadow">
                    <h2 class="sr-only" id="profile-overview-title">Hire Contract</h2>
                    <div class="bg-white p-6">
                    <div class="sm:flex sm:items-center sm:justify-between">
                        <div class="sm:flex sm:space-x-5">
                        <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
                            <p class="text-sm font-medium text-gray-600">TCL Tankers</p>
                            <p class="text-xl font-bold text-gray-900 sm:text-2xl">{{ $check_type }} Hire Checklist</p>
                            <p class="text-sm font-medium text-gray-400">To be completed by TCL and customer upon collection.</p>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                @include('app.check_list_rigids.form-inputs')
                <div class="mt-10">
                    <a href="{{ route('check-list-rigids.index') }}" class="button">
                        <i class="mr-1 icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>
                    <button type="submit" class="button button-primary float-right">
                        <i class="mr-1 icon ion-md-save"></i>
                        Save
                    </button>
                    <a href="{{route('hires.edit', ['hire' => $hire])}}" id="abort_rigid_btn" class="bg-orange-500 hover:bg-orange-700 text-white py-1 px-4 rounded-md float-right mr-5 cursor-pointer">
                        <i class="mr-1 icon ion-md-refresh text-primary"></i>
                        @lang('crud.common.clear')
                    </a>
                </div>
            </form>
        </div>
    </section>
</main>
@endsection
<script type="text/javascript">
    var user = {!! json_encode(auth()->user()) !!}
</script>

resources/views/app/check_list_rigids/edit.blade.php
@extends('layouts.app')
@section('styles')
<link rel="stylesheet" href="{{ asset('css/scroll_down.css') }}"> 
@endsection
@section('content')
<main class="-mt-28 pb-8">
    <section aria-labelledby="hire-contract">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <x-slot name="title">
                <a href="{{ route('check-list-rigids.index') }}" class="mr-4"
                    ><i class="mr-1 icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.check_list_rigids.edit_title')
            </x-slot>
            
            <x-form
                method="PUT"
                action="{{ route('check-list-rigids.update', $checkListRigid) }}"
                class="mt-4"
                enctype="multipart/form-data"
                id="check-list-rigids-edit-form"
            >
                <div class="mb-10 rounded-lg bg-white overflow-hidden shadow">
                    <h2 class="sr-only" id="profile-overview-title">Hire Contract</h2>
                    <div class="bg-white p-6 relative">
                    <div class="sm:flex sm:items-center sm:justify-between">
                        <div class="sm:flex sm:space-x-5 tanker-header">
                            <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
                                <p class="text-sm font-medium text-gray-600">TCL Tankers</p>
                                <p class="text-xl font-bold text-gray-900 sm:text-2xl">{{ $check_type }} Hire Checklist</p>
                                <p class="text-sm font-medium text-gray-400">To be completed by TCL and customer upon collection.</p>
                            </div>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-600 font-bold absolute top-3 right-16" style="right: 3.5%">Please sign here</p>
                            <svg class="arrows down cursor-pointer">            
                                <path class="a1" d="M0 0 L20 25 L40 0"></path>
                                <path class="a2" d="M0 20 L20 45 L40 20"></path>
                                <path class="a3" d="M0 40 L20 65 L40 40"></path>
                            </svg>
                        </div>
                    </div>
                    </div>
                </div>
                @include('app.check_list_rigids.form-inputs')
                <div class="mt-10">
                    <a href="{{ route('check-list-rigids.index') }}" class="button">
                        <i class="mr-1 icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <a
                        href="{{ route('check-list-rigids.create') }}"
                        class="button"
                    >
                        <i class="mr-1 icon ion-md-add text-primary"></i>
                        Save
                    </a>
                    @if(!isset($url_link))
                        <button type="submit" class="button button-primary float-right">
                            <i class="mr-1 icon ion-md-save"></i>
                            Save
                        </button>
                    @endif
                </div>
            </x-form>
        </div>
    </section>
</main>
@endsection

resources/views/app/check_list_rigids/index.blade.php
@extends('layouts.app')

@section('content')


<!-- <main class="-mt-28 pb-8">
    <section aria-labelledby="hire-contract">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <x-slot name="title">
                @lang('crud.check_list_rigids.index_title')
            </x-slot>
        </div>
        <div class="mx-auto px-4 md:px-6">
            <div class="flex justify-between">
                <x-slot name="title">
                    @lang('crud.check_list_rigids.index_title')
                </x-slot>
            </div>
            <main class="-mt-24 pb-8">
    <section aria-labelledby="hire-contract"> -->

<main class="-mt-24 pb-8">
	<section aria-labelledby="hire-contract">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
        {{-- START TOP CARD --}}
        <div class="mb-10 rounded-lg bg-white overflow-hidden shadow">
            <h2 class="sr-only" id="profile-overview-title">@lang('crud.check_list_rigids.index_title')</h2>
            <div class="bg-white p-6">
              <div class="sm:flex sm:items-center sm:justify-between">
                <div class="sm:flex sm:space-x-5">
                  <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
                    <p class="text-sm font-medium text-gray-600">TCL Tankers</p>
                    <p class="text-xl font-bold text-gray-900 sm:text-2xl">@lang('crud.check_list_rigids.index_title')</p>
                    <p class="text-sm font-medium text-gray-400">.</p>
                  </div>
                </div>
              </div>

              {{-- END SEARCH --}}
							<div class="mt-4 mb-5">
									<div class="flex flex-wrap">
											<div class="md:w-1/2">
													<form>
															<div class="flex items-stretch w-full">
																	<x-inputs.text
																			id="indexSearch"
																			name="search"
																			value="{{ $search ?? '' }}"
																			placeholder="{{ __('crud.common.search') }}"
																			autocomplete="off"
																	></x-inputs.text>

																	<div class="ml-1">
																			<button
																					type="submit"
																					class="button button-primary"
																			>
																					<i class="icon ion-md-search"></i>
																			</button>
																	</div>
															</div>
													</form>
											</div>
											<div class="md:w-1/2 text-right">
													@can('create', App\Models\CheckListRigid::class)
													<a
															href="{{ route('check-list-rigids.create') }}"
															class="button button-primary"
													>
															<i class="mr-1 icon ion-md-add"></i>
															@lang('crud.common.create')
													</a>
													@endcan
											</div>
									</div>
							</div>

							<div class="block w-full overflow-auto scrolling-touch">
									<table class="w-full max-w-full mb-4 bg-transparent">
											<thead>
													<tr>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.checklist_type')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.status_string')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.hirer_name')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.hirer_position')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.hirer_signature')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.hirer_sign_date')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.tcl_name')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.tcl_position')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.tcl_signature')
															</th>
															<th class="px-4 py-3 text-left">
																	@lang('crud.check_list_rigids.inputs.tcl_sign_date')
															</th>
															<th class="px-4 py-3 text-center">
																	@lang('crud.common.actions')
															</th>
													</tr>
											</thead>
											<tbody>
													@forelse($checkListRigids as $checkListRigid)
													<tr class="hover:bg-gray-50">
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->checklist_type ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->status_string ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->hirer_name ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->hirer_position ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->hirer_signature ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->hirer_sign_date ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->tcl_name ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->tcl_position ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->tcl_signature ?? '-' }}
															</td>
															<td class="px-4 py-3 text-left">
																	{{ $checkListRigid->tcl_sign_date ?? '-' }}
															</td>
															<td class="px-4 py-3 text-center" style="width: 134px;">
																	<div
																			role="group"
																			aria-label="Row Actions"
																			class="relative inline-flex align-middle"
																	>
																			@can('update', $checkListRigid)
																			<a
																					href="{{ route('check-list-rigids.edit', $checkListRigid) }}"
																					class="mr-1"
																			>
																					<button type="button" class="button">
																							<i class="icon ion-md-create"></i>
																					</button>
																			</a>
																			@endcan @can('view', $checkListRigid)
																			<a
																					href="{{ route('check-list-rigids.show', $checkListRigid) }}"
																					class="mr-1"
																			>
																					<button type="button" class="button">
																							<i class="icon ion-md-eye"></i>
																					</button>
																			</a>
																			@endcan @can('delete', $checkListRigid)
																			<form
																					action="{{ route('check-list-rigids.destroy', $checkListRigid) }}"
																					method="POST"
																					onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
																			>
																					@csrf @method('DELETE')
																					<button type="submit" class="button">
																							<i
																									class="icon ion-md-trash text-red-600"
																							></i>
																					</button>
																			</form>
																			@endcan
																	</div>
															</td>
													</tr>
													@empty
													<tr>
															<td colspan="11">
																	@lang('crud.common.no_items_found')
															</td>
													</tr>
													@endforelse
											</tbody>
											<tfoot>
													<tr>
															<td class="pt-10" colspan="11">
																	{!! $checkListRigids->render() !!}
															</td>
													</tr>
											</tfoot>
									</table>
							</div>
						</div>
					</div>
        </div>
			</div>
		</div>
	</section>
</main>
@endsection