routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\QrController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HireController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TankerController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\CheckListNrController;
use App\Http\Controllers\CheckListRigidController;
use App\Http\Controllers\CheckListMilkController;
use App\Http\Controllers\CheckListFoodController;
use App\Http\Controllers\CheckListVacuumController;
use App\Http\Controllers\CheckListWasteController;
use App\Http\Controllers\CheckListPetrolController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LinkController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\TCLEmailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great! Note
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');



Route::get('/newhiremockup', function () {
    return view('newbooking');
});

Route::get('/checkoutmockup', function () {
    return view('checkout');
});
Route::get('/rigid', function () {
    return view('rigid');
});

Auth::routes();

Route::post('videosStore', 'App\Http\Controllers\MediaController@saveVideo')->name('videos.store');
Route::post('imagesStore', 'App\Http\Controllers\MediaController@saveImage')->name('images.store');

Route::get('contract/{uuid}', [ContractController::class, 'customerSign'])->name('contract_link');
Route::put('contract/{hire}',  [ContractController::class, 'store'])->name('contract.store');

Route::get('checkListNR/{uuid}', [ContractController::class, 'checklistNr'])->name('checklist_nr_link');
Route::get('checkListRigid/{uuid}', [ContractController::class, 'checklistRigid'])->name('checklist_rigid_link');
Route::get('checkListMilk/{uuid}', [ContractController::class, 'checklistMilk'])->name('checklist_milk_link');
Route::get('checkListFood/{uuid}', [ContractController::class, 'checklistFood'])->name('checklist_food_link');
Route::get('checkListVacuum/{uuid}', [ContractController::class, 'checklistVacuum'])->name('checklist_vacuum_link');
Route::get('checkListWaste/{uuid}', [ContractController::class, 'checklistWaste'])->name('checklist_waste_link');
Route::get('checkListPetrol/{uuid}', [ContractController::class, 'checklistPetrol'])->name('checklist_petrol_link');

Route::get('sendMail', [TCLEmailController::class, 'sendHireEmailToCustomer'])->name('email');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::get('home', [HomeController::class, 'index'])->name('home');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('settings', SettingController::class);
        Route::resource('tankers', TankerController::class);
        Route::resource('qrs', QrController::class);
        Route::resource('logs', LogController::class);
        Route::resource('companies', CompanyController::class);
        Route::resource('users', UserController::class);
        Route::resource('hires', HireController::class);
        Route::resource('check-list-n-rs', CheckListNrController::class);
        Route::resource('check-list-rigids', CheckListRigidController::class);
        Route::resource('check-list-milks', CheckListMilkController::class);
        Route::resource('check-list-foods', CheckListFoodController::class);
        Route::resource('check-list-vacuums', CheckListVacuumController::class);
        Route::resource('check-list-wastes', CheckListWasteController::class);
        Route::resource('check-list-petrols', CheckListPetrolController::class);
        Route::get('link/{fleet_num}', [LinkController::class, 'showTanker']);

        Route::get('user/profile', [ProfileController::class, 'index'])->name('user.profile');
        Route::post('user/avatarUpload', [ProfileController::class, 'avatarUpload'])->name('user.avatarUpload');
        Route::post('user/profileUpdate', [ProfileController::class, 'profileUpdate'])->name('user.profileUpdate');
        Route::post('user/jobInfoUpdate', [ProfileController::class, 'jobInfoUpdate'])->name('user.jobInfoUpdate');
        Route::post('user/changePwd', [ProfileController::class, 'changePwd'])->name('user.changePwd');        
        Route::post('tankers/archive', [TankerController::class, 'archive'])->name('tankers.archive');
        Route::post('tankers/refresh', [TankerController::class, 'refresh'])->name('tankers.refresh');
        Route::post('hires/documentUpload', [HireController::class, 'documentUpload'])->name('hires.documentUpload');
    });

Route::get('/{any}', function(){
    return redirect()->route("welcome");
});

app/Http/Controllers/Api/HireController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Hire;
use Illuminate\Http\Request;
use App\Http\Resources\HireResource;
use App\Http\Controllers\Controller;
use App\Http\Resources\HireCollection;
use App\Http\Requests\HireStoreRequest;
use App\Http\Requests\HireUpdateRequest;

class HireController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', Hire::class);

        $search = $request->get('search', '');

        $hires = Hire::search($search)
            ->latest()
            ->paginate();

        return new HireCollection($hires);
    }

    /**
     * @param \App\Http\Requests\HireStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(HireStoreRequest $request)
    {
        $this->authorize('create', Hire::class);

        $validated = $request->validated();

        $hire = Hire::create($validated);

        return new HireResource($hire);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Hire $hire)
    {
        $this->authorize('view', $hire);

        return new HireResource($hire);
    }

    /**
     * @param \App\Http\Requests\HireUpdateRequest $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function update(HireUpdateRequest $request, Hire $hire)
    {
        $this->authorize('update', $hire);

        $validated = $request->validated();

        $hire->update($validated);

        return new HireResource($hire);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Hire $hire)
    {
        $this->authorize('delete', $hire);

        $hire->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/HireController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hire;
use App\Models\Tanker;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Http\Requests\HireStoreRequest;
use App\Http\Requests\HireUpdateRequest;
use Webpatser\Uuid\Uuid;

class HireController extends Controller
{

    public function current_week_range(&$start_date, &$end_date) {
        $current=time();
        $today = date("Y-m-d",$current);

        $ts = strtotime($today);

        $start = (date('w', $ts) == 0) ? $ts : strtotime('last sunday', $ts);

        $start_date = date('Y-m-d', $start);
        $end_date = date('Y-m-d', strtotime('next saturday', $start));
    }


    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view-any', Hire::class);


        $title = 'TCL Tanker Track';
        $search = $request->get('search', '');        
        
        $hires = Hire::join('companies', 'companies.id', '=', 'hires.company_id')
        ->join('tankers', 'tankers.id', '=', 'hires.tanker_id')        
        ->where(function ($query)use ($search) {
            $query->orWhere('hires.order_num', 'like', '%'.$search.'%')                    
                  ->orWhere('hires.start_date', 'like', '%'.$search.'%')
                  ->orWhere('hires.end_date', 'like', '%'.$search.'%')
                  ->orWhere('companies.company', 'like', '%'.$search.'%')
                  ->orWhere('tankers.fleet_num', 'like', '%'.$search.'%');
        })
        // ->get(['hires.*', 'companies.company', 'tankers.fleet_num']);        
        // ->latest()
        ->select('hires.*')
        ->orderByDesc('hires.updated_at')
        ->paginate(20);
        
        $status = $request->status;
        if ($status) {
            $this->current_week_range($start_date, $end_date);
            switch ($status) {
                case 'active' :
                    $hires = Hire::where(function($query) use($start_date, $end_date){
                        $query->where("start_date", '>=', $start_date)->where('start_date', '<=', $end_date);
                    })->orWhere(function ($query) use ($start_date, $end_date) {
                        $query->where("end_date", '>=', $start_date)->where('end_date', '<=', $end_date);
                    })->search($search)
                    ->latest()
                    ->paginate(20);
                    break;
                case 'pending':
                    $title = "Pending Contracts";
                    $hires = Hire::where('status', 'pending')
                    ->search($search)
                    ->latest()
                    ->paginate(20);
                    break;
                case 'signed':
                    $hires = Hire::where('status', 'signed')
                    ->search($search)
                    ->latest()
                    ->paginate(20);
                    break;
                case 'onHire':
                    $hires = Hire::where('status', 'onHire')
                    ->search($search)
                    ->latest()
                    ->paginate(20);
                    break;
            }
        }
        return view('app.hires.index', ['hires'=>$hires, 'search' => $search, 'title' => $title]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('create', Hire::class);

        $companies = Company::all();
        $tankers = Tanker::where('usage', '=', false)->where('archive', '=', false)->select(['id','fleet_num'])->get();

        return view('app.hires.create', compact('companies', 'tankers'));
    }

    /**
     * @param \App\Http\Requests\HireStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(HireStoreRequest $request)
    {
        $this->authorize('create', Hire::class);
        $validated = $request->validated();
        $validated['uuid'] = Str::uuid();
        $validated['hirer_signature'] = str_replace(env('APP_URL'), '', $validated['hirer_signature']);
        $validated['tcl_signature'] = str_replace(env('APP_URL'), '', $validated['tcl_signature']);
        $sel_company = Company::where('company', '=' , $request->company_id)->first();
        $validated['company_id'] = $sel_company->id;
        $hire = Hire::create($validated);        
        $hire->attached_doc = $request->document_path;
        $hire->save();

        $tanker = Tanker::find($hire->tanker_id);        
        $tanker->usage = true;
        $tanker->save();

        if($request->hirer_signature == "/img/sign.png" && $request->tcl_signature == "/img/sign.png") {
            $hire->status = "draft";
        }
        else if($request->hirer_signature == "/img/sign.png" && $request->tcl_signature != "/img/sign.png") {
            $hire->status = "pending";
        }
        else if($request->hirer_signature != "/img/sign.png" && $request->tcl_signature != "/img/sign.png") {
            $hire->status = "signed";
        }
        $hire->update($validated);
        return redirect()
            ->route('hires.edit', $hire)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Hire $hire)
    {
        $this->authorize('view', $hire);

        return view('app.hires.show', compact('hire'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Hire $hire)
    {
        $this->authorize('update', $hire);
        $companies = Company::all();
        $tankers = Tanker::where('usage', '=', false)->where('archive', '=', false)->select(['id','fleet_num'])->get();
        $cnt_tankers = count($tankers);
        $tankers[$cnt_tankers] = $hire->tanker;
        return view('app.hires.edit', compact('hire', 'companies', 'tankers'));
    }

    /**
     * @param \App\Http\Requests\HireUpdateRequest $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function update(HireUpdateRequest $request, Hire $hire)
    {
        $this->authorize('update', $hire);

        $validated = $request->validated();
        $validated['hirer_signature'] = str_replace(env('APP_URL'), '', $validated['hirer_signature']);
        $validated['tcl_signature'] = str_replace(env('APP_URL'), '', $validated['tcl_signature']);
        $sel_company = Company::where('company', '=' , $request->company_id)->first();
        $validated['company_id'] = $sel_company->id;
        if($request->hirer_signature == "/img/sign.png" && $request->tcl_signature == "/img/sign.png") {
            $hire->status = "draft";
        }
        else if($request->hirer_signature == "/img/sign.png" && $request->tcl_signature != "/img/sign.png") {
            $hire->status = "pending";
        }
        else if($request->hirer_signature != "/img/sign.png" && $request->tcl_signature != "/img/sign.png" && $hire->status == 'pending') {
            $hire->status = "signed";
        }
        $old_attached_doc = $hire->attached_doc;
        $hire->update($validated);
        $hire->attached_doc = $request->document_path;
        $hire->save();
        if($hire->status == "signed" && $hire->attached_doc != $old_attached_doc){
            $attached_docs_url = explode(";", $hire->attached_doc);
            if($attached_docs_url[0] == '')
                $attached_docs_url = null;
            $details = [
                'hirer_name' => $hire->hirer_name,
                'link_url' => route('contract_link', ['uuid' => $hire->uuid]),
                'attached_docs_url' => $attached_docs_url,
                'isUpdatedDocs' => "true",
            ];
        
            $email_address = $hire->company->email;
    
            \Mail::to($email_address)->send(new \App\Mail\SendCustomerMail($details));  
        }
        return redirect()
            ->route('hires.edit', $hire)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Hire $hire
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Hire $hire)
    {
        $this->authorize('delete', $hire);

        $hire->delete();

        return redirect()
            ->route('hires.index')
            ->withSuccess(__('crud.common.removed'));
    }

    public function documentUpload(Request $request)
    {
        $docs = $request->file('document');
        for($i = 0; $i < count($docs); $i ++)
        {
            $filename = time()."__".$i.'.'.$docs[$i]->guessExtension();
            $path = $docs[$i]->storeAs('public/documents',$filename);
            $dest[$i] = '/storage/documents/'.$filename;
        }

        return response()->json([
            'path' => $dest,
            'success' => 'success'
        ], 200);
    }
}

resources/views/app/hires/create.blade.php
@extends('layouts.app')
@section('content')

<main class="-mt-28 pb-8">
    <section aria-labelledby="hire-contract">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <x-slot name="title">
                <a href="{{ route('hires.index') }}" class="mr-4"
                    ><i class="mr-1 icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.hires.create_title')
            </x-slot>

            <form method="POST" role="form" action="{{ route('hires.store') }}" class="mt-4" id="hire_create_form">
                {{ csrf_field() }}
                @include('app.hires.form-inputs')
                <div class="mt-10">
                    <a href="{{ route('hires.index') }}" class="button">
                        <i class="mr-1 icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>                    
                    <button type="submit" class="button button-primary float-right border-none">
                        <i class="mr-1 icon ion-md-save"></i>
                        Save
                    </button>
                    <a id="abort_btn" class="bg-orange-500 hover:bg-orange-700 text-white py-1 px-4 rounded-md float-right mr-5 cursor-pointer">
                        <i class="mr-1 icon ion-md-refresh text-primary"></i>
                        @lang('crud.common.clear')
                    </a>
                </div>
            </form>
        </div>
    </section>
</main>
@endsection
<script type="text/javascript">
    var user = {!! json_encode(auth()->user()) !!}
</script>

resources/views/app/hires/edit.blade.php
@extends('layouts.app')

@section('content')
<main class="-mt-28 pb-8">
    <section aria-labelledby="hire-contract">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <x-slot name="title">
                <a href="{{ route('hires.index') }}" class="mr-4"
                    ><i class="mr-1 icon ion-md-arrow-back"></i
                ></a>
                @lang('crud.hires.edit_title')
            </x-slot>

            <x-form
                method="PUT"
                action="{{ route('hires.update', $hire) }}"
                class="mt-4"
            >
                @include('app.hires.form-inputs')                
                <div class="mt-10">
                    <a href="{{ route('hires.index') }}" class="button">
                        <i class="mr-1 icon ion-md-return-left text-primary"></i>
                        @lang('crud.common.back')
                    </a>

                    <!-- <a href="{{ route('hires.create') }}" class="button">
                        <i class="mr-1 icon ion-md-add text-primary"></i>
                        Save
                    </a>                                          -->
                    @if($hire->status == 'pending')
                    
                    <a href="{{route('email', ['hire_id' => $hire])}}" class="bg-yellow-500 hover:bg-yellow-700 text-white py-1 px-4 rounded-md float-right ml-5">
                    <span class="mr-2">Sign Request To Client</span>
                        <i class="icon ion-md-return-right text-primary"></i>
                    </a>
                    @endif                                        
                    
                    @if($hire->status == 'onHire' || $hire->status == 'offHire')                        
                        @if($hire->tanker->type == 'Non-Rigid')
                            @if(count($hire->checkListsNRs) == 1)   
                            <a href="{{route('check-list-n-rs.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsNRs) == 2)
                            <a href="{{route('check-list-n-rs.edit', ['check_list_n_r' => $hire->checkListsNRs[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Rigid')
                            @if(count($hire->checkListRigids) == 1)   
                            <a href="{{route('check-list-rigids.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListRigids) == 2)
                            <a href="{{route('check-list-rigids.edit', ['check_list_rigid' => $hire->checkListRigids[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif 
                        @if($hire->tanker->type == 'Milk')
                            @if(count($hire->checkListsMilks) == 1)   
                            <a href="{{route('check-list-milks.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsMilks) == 2)
                            <a href="{{route('check-list-milks.edit', ['check_list_milk' => $hire->checkListsMilks[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Food')
                            @if(count($hire->checkListsFoods) == 1)   
                            <a href="{{route('check-list-foods.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsFoods) == 2)
                            <a href="{{route('check-list-foods.edit', ['check_list_food' => $hire->checkListsFoods[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Vacuum')
                            @if(count($hire->checkListsVacuums) == 1)   
                            <a href="{{route('check-list-vacuums.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsVacuums) == 2)
                            <a href="{{route('check-list-vacuums.edit', ['check_list_vacuum' => $hire->checkListsVacuums[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Waste')
                            @if(count($hire->checkListsWastes) == 1)   
                            <a href="{{route('check-list-wastes.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsWastes) == 2)
                            <a href="{{route('check-list-wastes.edit', ['check_list_waste' => $hire->checkListsWastes[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Petrol')
                            @if(count($hire->checkListsPetrols) == 1)   
                            <a href="{{route('check-list-petrols.create', ['hire_id' => $hire, 'check_list_type' => 'Off' ])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsPetrols) == 2)
                            <a href="{{route('check-list-petrols.edit', ['check_list_petrol' => $hire->checkListsPetrols[1]])}}" class="bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif  
                            <span class="mr-2">Off-Hire CheckList</span>
                            <i class="icon ion-md-return-right text-primary"></i>
                        </a>     
                    @endif           
                    @if($hire->status != 'pending' && $hire->status != 'draft')
                        @if($hire->tanker->type == 'Non-Rigid')
                            @if(count($hire->checkListsNRs) == 0)   
                            <a href="{{route('check-list-n-rs.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsNRs) != 0)
                            <a href="{{route('check-list-n-rs.edit', ['check_list_n_r' => $hire->checkListsNRs[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Rigid')
                            @if(count($hire->checkListRigids) == 0)   
                            <a href="{{route('check-list-rigids.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListRigids) != 0)
                            <a href="{{route('check-list-rigids.edit', ['check_list_rigid' => $hire->checkListRigids[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Milk')
                            @if(count($hire->checkListsMilks) == 0)   
                            <a href="{{route('check-list-milks.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsMilks) != 0)
                            <a href="{{route('check-list-milks.edit', ['check_list_milk' => $hire->checkListsMilks[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Food')
                            @if(count($hire->checkListsFoods) == 0)   
                            <a href="{{route('check-list-foods.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsFoods) != 0)
                            <a href="{{route('check-list-foods.edit', ['check_list_food' => $hire->checkListsFoods[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Vacuum')
                            @if(count($hire->checkListsVacuums) == 0)   
                            <a href="{{route('check-list-vacuums.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsVacuums) != 0)
                            <a href="{{route('check-list-vacuums.edit', ['check_list_vacuum' => $hire->checkListsVacuums[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Waste')
                            @if(count($hire->checkListsWastes) == 0)   
                            <a href="{{route('check-list-wastes.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsWastes) != 0)
                            <a href="{{route('check-list-wastes.edit', ['check_list_waste' => $hire->checkListsWastes[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                        @if($hire->tanker->type == 'Petrol')
                            @if(count($hire->checkListsPetrols) == 0)   
                            <a href="{{route('check-list-petrols.create', ['hire_id' => $hire, 'check_list_type' => 'On' ])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                            @if(count($hire->checkListsPetrols) != 0)
                            <a href="{{route('check-list-petrols.edit', ['check_list_petrol' => $hire->checkListsPetrols[0]])}}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md float-right ml-5">
                            @endif
                        @endif
                            <span class="mr-2">On-Hire CheckList</span>
                            <i class="icon ion-md-return-right text-primary"></i>
                        </a>
                    @endif            
                    
                    <button type="submit" class="button button-primary float-right border-none">
                        <i class="mr-1 icon ion-md-save"></i>
                        Save
                    </button>
                </div>
            </x-form>
        </div>
    </section>
</main>
@endsection