routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\QrController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HireController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TankerController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\CheckListNrController;
use App\Http\Controllers\CheckListRigidController;
use App\Http\Controllers\CheckListMilkController;
use App\Http\Controllers\CheckListFoodController;
use App\Http\Controllers\CheckListVacuumController;
use App\Http\Controllers\CheckListWasteController;
use App\Http\Controllers\CheckListPetrolController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LinkController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\TCLEmailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great! Note
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');



Route::get('/newhiremockup', function () {
    return view('newbooking');
});

Route::get('/checkoutmockup', function () {
    return view('checkout');
});
Route::get('/rigid', function () {
    return view('rigid');
});

Auth::routes();

Route::post('videosStore', 'App\Http\Controllers\MediaController@saveVideo')->name('videos.store');
Route::post('imagesStore', 'App\Http\Controllers\MediaController@saveImage')->name('images.store');

Route::get('contract/{uuid}', [ContractController::class, 'customerSign'])->name('contract_link');
Route::put('contract/{hire}',  [ContractController::class, 'store'])->name('contract.store');

Route::get('checkListNR/{uuid}', [ContractController::class, 'checklistNr'])->name('checklist_nr_link');
Route::get('checkListRigid/{uuid}', [ContractController::class, 'checklistRigid'])->name('checklist_rigid_link');
Route::get('checkListMilk/{uuid}', [ContractController::class, 'checklistMilk'])->name('checklist_milk_link');
Route::get('checkListFood/{uuid}', [ContractController::class, 'checklistFood'])->name('checklist_food_link');
Route::get('checkListVacuum/{uuid}', [ContractController::class, 'checklistVacuum'])->name('checklist_vacuum_link');
Route::get('checkListWaste/{uuid}', [ContractController::class, 'checklistWaste'])->name('checklist_waste_link');
Route::get('checkListPetrol/{uuid}', [ContractController::class, 'checklistPetrol'])->name('checklist_petrol_link');

Route::get('sendMail', [TCLEmailController::class, 'sendHireEmailToCustomer'])->name('email');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::get('home', [HomeController::class, 'index'])->name('home');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('settings', SettingController::class);
        Route::resource('tankers', TankerController::class);
        Route::resource('qrs', QrController::class);
        Route::resource('logs', LogController::class);
        Route::resource('companies', CompanyController::class);
        Route::resource('users', UserController::class);
        Route::resource('hires', HireController::class);
        Route::resource('check-list-n-rs', CheckListNrController::class);
        Route::resource('check-list-rigids', CheckListRigidController::class);
        Route::resource('check-list-milks', CheckListMilkController::class);
        Route::resource('check-list-foods', CheckListFoodController::class);
        Route::resource('check-list-vacuums', CheckListVacuumController::class);
        Route::resource('check-list-wastes', CheckListWasteController::class);
        Route::resource('check-list-petrols', CheckListPetrolController::class);
        Route::get('link/{fleet_num}', [LinkController::class, 'showTanker']);

        Route::get('user/profile', [ProfileController::class, 'index'])->name('user.profile');
        Route::post('user/avatarUpload', [ProfileController::class, 'avatarUpload'])->name('user.avatarUpload');
        Route::post('user/profileUpdate', [ProfileController::class, 'profileUpdate'])->name('user.profileUpdate');
        Route::post('user/jobInfoUpdate', [ProfileController::class, 'jobInfoUpdate'])->name('user.jobInfoUpdate');
        Route::post('user/changePwd', [ProfileController::class, 'changePwd'])->name('user.changePwd');        
        Route::post('tankers/archive', [TankerController::class, 'archive'])->name('tankers.archive');
        Route::post('tankers/refresh', [TankerController::class, 'refresh'])->name('tankers.refresh');
        Route::post('hires/documentUpload', [HireController::class, 'documentUpload'])->name('hires.documentUpload');
    });

Route::get('/{any}', function(){
    return redirect()->route("welcome");
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) 
    {
        $this->authorize('list', Role::class);

        $search = $request->get('search', '');
        $roles = Role::where('name', 'like', "%{$search}%")->paginate(10);

        return view('app.roles.index')
            ->with('roles', $roles)
            ->with('search', $search);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() 
    {
        $this->authorize('create', Role::class);

        $permissions = Permission::all();

        return view('app.roles.create')->with('permissions', $permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) 
    {
        $this->authorize('create', Role::class);

        $data = $this->validate($request, [
            'name' => 'required|unique:roles|max:32',
            'permissions' => 'array',
        ]);

        $role = Role::create($data);

        $permissions = Permission::find($request->permissions);
        $role->syncPermissions($permissions);

        return redirect()
            ->route('roles.edit', $role->id)
            ->withSuccess(__('crud.common.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role) 
    {
        $this->authorize('view', Role::class);

        return view('app.roles.show')->with('role', $role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role) 
    {
        $this->authorize('update', $role);

        $permissions = Permission::all();

        return view('app.roles.edit')
            ->with('role', $role)
            ->with('permissions', $permissions);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role) 
    {
        $this->authorize('update', $role);

        $data = $this->validate($request, [
            'name' => 'required|max:32|unique:roles,name,'.$role->id,
            'permissions' => 'array',
        ]);
        
        $role->update($data);

        $permissions = Permission::find($request->permissions);
        $role->syncPermissions($permissions);

        return redirect()
            ->route('roles.edit', $role->id)
            ->withSuccess(__('crud.common.saved'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Spatie\Permission\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete', $role);

        $role->delete();

        return redirect()
            ->route('roles.index')
            ->withSuccess(__('crud.common.removed'));
    }
}

resources/views/app/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="mx-auto px-4 md:px-6">
    <x-partials.card>
        <x-slot name="title">
            <a href="{{ route('roles.index') }}" class="mr-4"
                ><i class="mr-1 icon ion-md-arrow-back"></i
            ></a>
            @lang('crud.roles.create_title')
        </x-slot>

        <x-form method="POST" action="{{ route('roles.store') }}" class="mt-4">
            @include('app.roles.form-inputs')

            <div class="mt-10">
                <a href="{{ route('roles.index') }}" class="button">
                    <i class="mr-1 icon ion-md-return-left text-primary"></i>
                    @lang('crud.common.back')
                </a>

                <button type="submit" class="button button-primary float-right">
                    <i class="mr-1 icon ion-md-save"></i>
                    Save
                </button>
            </div>
        </x-form>
    </x-partials.card>
</div>
@endsection

resources/views/app/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="mx-auto px-4 md:px-6">
    <x-partials.card>
        <x-slot name="title">
            <a href="{{ route('roles.index') }}" class="mr-4"
                ><i class="mr-1 icon ion-md-arrow-back"></i
            ></a>
            @lang('crud.roles.edit_title')
        </x-slot>

        <x-form
            method="PUT"
            action="{{ route('roles.update', $role) }}"
            class="mt-4"
        >
            @include('app.roles.form-inputs')

            <div class="mt-10">
                <a href="{{ route('roles.index') }}" class="button">
                    <i class="mr-1 icon ion-md-return-left text-primary"></i>
                    @lang('crud.common.back')
                </a>

                <a href="{{ route('roles.create') }}" class="button">
                    <i class="mr-1 icon ion-md-add text-primary"></i>
                    Save
                </a>

                <button type="submit" class="button button-primary float-right">
                    <i class="mr-1 icon ion-md-save"></i>
                    Save
                </button>
            </div>
        </x-form>
    </x-partials.card>
</div>
@endsection

resources/views/app/roles/form-inputs.blade.php
@php $editing = isset($role) @endphp

<div class="flex flex-wrap">
    <x-inputs.group class="w-full">
        <x-inputs.text
            name="name"
            label="Name"
            value="{{ old('name', ($editing ? $role->name : '')) }}"
        ></x-inputs.text>
    </x-inputs.group>

    <div class="px-4 my-4">
        <h4 class="font-bold text-lg">Assign @lang('crud.permissions.name')</h4>

        <div class="py-2 grid grid-cols-5 px-4">
            @foreach ($permissions as $permission)
            <div class="px-6">
                <x-inputs.checkbox
                    id="permission{{ $permission->id }}"
                    name="permissions[]"
                    label="{{ ucfirst($permission->name) }}"
                    value="{{ $permission->id }}"
                    :checked="isset($role) ? $role->hasPermissionTo($permission) : false"
                    :add-hidden-value="false"
                ></x-inputs.checkbox>
            </div>
            @endforeach
        </div>
    </div>
</div>

resources/views/app/roles/index.blade.php
@extends('layouts.app')

@section('content')

<main class="-mt-24 pb-8">
    <section aria-labelledby="hire-contract">

    <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">

        {{-- START TOP CARD --}}
        <div class="mb-10 rounded-lg bg-white overflow-hidden shadow">
            <h2 class="sr-only" id="profile-overview-title">@lang('crud.roles.index_title')</h2>
            <div class="bg-white p-6">
              <div class="sm:flex sm:items-center sm:justify-between">
                <div class="sm:flex sm:space-x-5">
                  <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
                    <p class="text-sm font-medium text-gray-600">TCL Tankers</p>
                    <p class="text-xl font-bold text-gray-900 sm:text-2xl">@lang('crud.roles.index_title')</p>
                    <p class="text-sm font-medium text-gray-400">.</p>
                  </div>
                </div>
              </div>

              {{-- START CONTENT IN TOP CARD --}}
              <div class="mt-4 mb-5">
                <div class="flex flex-wrap float-right pr-4">
                    <div class="md:w-1/2 text-right">
                        @can('create', App\Models\Role::class)
                        <a
                            href="{{ route('roles.create') }}"
                            class="button button-primary"
                        >
                            <i class="mr-1 icon ion-md-add"></i>
                            @lang('crud.common.create')
                        </a>
                        @endcan
                    </div>
                </div>
            </div>

            <div class="block w-full overflow-auto scrolling-touch">
                <table class="w-full max-w-full mb-4 bg-transparent">
                    <thead>
                        <tr>
                            <th class="px-4 py-3 text-left">
                                @lang('crud.roles.inputs.name')
                            </th>
                            <th class="px-4 py-3 text-center">
                                @lang('crud.common.actions')
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($roles as $role)
                        <tr class="hover:bg-gray-50">
                            <td class="px-4 py-3 text-left">
                                {{ $role->name ?? '-' }}
                            </td>
                            <td class="px-4 py-3 text-center" style="width: 134px;">
                                <div
                                    role="group"
                                    aria-label="Row Actions"
                                    class="relative inline-flex align-middle"
                                >
                                    @can('update', $role)
                                    <a
                                        href="{{ route('roles.edit', $role) }}"
                                        class="mr-1"
                                    >
                                        <button type="button" class="button">
                                            <i class="icon ion-md-create"></i>
                                        </button>
                                    </a>
                                    @endcan @can('view', $role)
                                    <a
                                        href="{{ route('roles.show', $role) }}"
                                        class="mr-1"
                                    >
                                        <button type="button" class="button">
                                            <i class="icon ion-md-eye"></i>
                                        </button>
                                    </a>
                                    @endcan @can('delete', $role)
                                    <form
                                        action="{{ route('roles.destroy', $role) }}"
                                        method="POST"
                                        onsubmit="return confirm('{{ __('crud.common.are_you_sure') }}')"
                                    >
                                        @csrf @method('DELETE')
                                        <button type="submit" class="button">
                                            <i
                                                class="icon ion-md-trash text-red-600"
                                            ></i>
                                        </button>
                                    </form>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="2">@lang('crud.common.no_items_found')</td>
                        </tr>
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="pt-10" colspan="2">
                                {!! $roles->render() !!}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
              {{-- END CONTENT IN TOP CARD --}}
            </div>
        </div>
        {{-- END TOP CARD --}}

        {{-- START CARD 2 --}}

        {{-- END CARD 2 --}}

    </div>
    </section>
</main>

@endsection

resources/views/app/roles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="mx-auto px-4 md:px-6">
    <x-partials.card>
        <x-slot name="title">
            <a href="{{ route('roles.index') }}" class="mr-4"
                ><i class="mr-1 icon ion-md-arrow-back"></i
            ></a>
            @lang('crud.roles.show_title')
        </x-slot>

        <div class="mt-4">
            <div class="mb-4">
                <h5 class="font-medium">@lang('crud.roles.inputs.name')</h5>
                <span>{{ $role->name ?? '-' }}</span>
            </div>
        </div>

        <div class="mt-10">
            <a href="{{ route('roles.index') }}" class="button">
                <i class="mr-1 icon ion-md-return-left"></i>
                @lang('crud.common.back')
            </a>

            @can('create', App\Models\Role::class)
            <a href="{{ route('roles.create') }}" class="button">
                <i class="mr-1 icon ion-md-add"></i> @lang('crud.common.create')
            </a>
            @endcan
        </div>
    </x-partials.card>
</div>
@endsection